# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/azureml/base:intelmpi2018.3-ubuntu16.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: conda install -c anaconda graphviz python-graphviz

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        python -c 'import graphviz; print(graphviz)'
        pip freeze > freeze.txt
    - name: Upload math result for job 1
      uses: actions/upload-artifact@v1
      with:
        name: freeze
        path: freeze.txt
        

  check:
    needs: [build]
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/azureml/base:intelmpi2018.3-ubuntu16.04
    
    steps:
    - name: Download math result for job 1
      uses: actions/download-artifact@v1
      with:
        name: freeze
    - name: print out freeze
      run: |
        find freeze
        cat freeze/freeze.txt
      
